version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-translate-audio:latest
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - flask_data:/data
    cpus: "2.0"
    cpuset: "0-3"
    deploy:
      resources:
        limits:
          cpus: "2.0"

volumes:
  deploy:
    resources:
    limits:
      cpus: "2.0"
      memory: 200M